# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    paths:
     - ".github/workflows/run_test_hw1.yaml"
     - "tasks/task1/list.cpp"
     - "!tasks/task1/tests/**"
  pull_request:
    paths:
     - ".github/workflows/run_test_hw1.yaml"
     - "tasks/task1/list.cpp"
     - "!tasks/task1/tests/**"


env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      working-directory: ${{github.workspace}}/tasks/task1/
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/tasks/task1/
      run: cmake --build ./build --target tests_run --config ${{env.BUILD_TYPE}}

    - name: Tests
      working-directory: ${{github.workspace}}/tasks/task1/
      run: build/tests_run
      shell: bash